name: Test & Release Package

on:
  push:
    tags: 
      - "*.*.*"
  workflow_dispatch:
    inputs:
      tags:

jobs:
  test-build:
    name: Test Package
    runs-on: macos-11
    
    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
